name: Pylint

on: [push]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint --max-line-length 7600 --indent-string "  " --disable "C, R0903, R1735, R0912, R0913, R0914, C0103, C0303, C0116, W0401, W0611, W0614, E0611, E0602, E0606, W0311, C0103" $(git ls-files '*.py')
